public class QuoteLineDiscount {
    public String type {get; set;}
    public String period_unit {get; set;}
    public String period {get; set;}
    public String percentage {get; set;}
    public String operation_type {get; set;}
    public String item_price_id {get; set;}
    public Boolean isPercentageDiscount {get; set;}
    public Boolean isOneTime {get; set;}
    public Boolean isLineItemDiscount {get; set;}
    public Boolean isInvoiceDiscount {get; set;}
    public Boolean isForever {get; set;}
    public Boolean isFixedDiscount {get; set;}
    public String id {get; set;}
    public String duration_type {get; set;}
    public String discountType;
    public String discountPercentage {get; set;}
    public String discountAmount {get; set;}
    public String currency_code {get; set;}
    public String cbId {get; set;}
    public String apply_on {get; set;}
    public String amount {get; set;}
}